# Generated by Django 3.2.18 on 2023-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='7065ed86a40346baaee46c919750dbf4', max_length=64, primary_key=True, serialize=False),
        ),
    ]
