# Generated by Django 3.2.18 on 2023-07-31 00:27

import adminpage.utils
from django.db import migrations, models
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_room_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRoom',
            fields=[
                ('id', models.CharField(default=adminpage.utils.generate_id, max_length=64, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=1000, null=True)),
                ('room_number', models.IntegerField(default='0')),
                ('date_booked', models.DateField(default=web.models.today)),
                ('date_end', models.DateField(default=web.models.today)),
                ('booked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date_created')),
            ],
            options={
                'ordering': ['date_booked'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=adminpage.utils.generate_id, max_length=64, primary_key=True, serialize=False),
        ),
    ]
