# Generated by Django 3.2.18 on 2023-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20230731_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='date_booked',
            new_name='booked_date',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='logroom',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
