# Generated by Django 3.2.18 on 2023-07-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='61918d12ed204b58a789711b141d9f92', max_length=64, primary_key=True, serialize=False),
        ),
    ]
