# Generated by Django 3.2.18 on 2023-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='4fe79ac120664d15814318e1b85aaeda', max_length=64, primary_key=True, serialize=False),
        ),
    ]
