# Generated by Django 3.2.18 on 2023-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='2d55f9b9e9d24cdcafb51fa25f65a9a4', max_length=64, primary_key=True, serialize=False),
        ),
    ]
