# Generated by Django 3.2.18 on 2023-07-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='423b1a9b231a4a66a8a39952cc3170e5', max_length=64, primary_key=True, serialize=False),
        ),
    ]
