# Generated by Django 3.2.18 on 2023-08-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='3537a17851274c1689f10b385fc21c8d', max_length=64, primary_key=True, serialize=False),
        ),
    ]
