# Generated by Django 3.2.18 on 2023-07-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='0ff81dad4cb14d5e969366c7191c0399', max_length=64, primary_key=True, serialize=False),
        ),
    ]
