# Generated by Django 3.2.18 on 2023-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='433f4becce3a4c8bbd52d4e389e4fec1', max_length=64, primary_key=True, serialize=False),
        ),
    ]
